### ISSUE TITLE
Any chance you can help me get started a bit?

### ISSUE THREAD

**Issue by reubeningber** [UnbounDev/node-strava-v3#27]
Trying to set up a way that upon logging in I receive back the athletes activities as describe [here](http://strava.github.io/api/v3/activities/)

**Comment by TimoSta** [comment]
Hi Reuben,
the [quick start guide](https://github.com/UnbounDev/node-strava-v3#quick-start) will give you a first starting point.

Could you maybe give some hints where in the process you are facing issues? Since I'm using the library successfully myself, I'd be more than happy to extend the guide with additional details.

**Comment by bryantee** [comment]
@reubeningber, Did you ever get through the issues?

**Comment by markstos** [comment]
This support question is almost a year old and can be closed-- there's no further response from the OP.
