### ISSUE TITLE
strava_config not working / have to provide access_token for every call

### ISSUE THREAD

**Issue by besseddrest** [UnbounDev/node-strava-v3#44]
I've followed the instructions to copy strava_config from node_modules into a new dir 'data' in the root of my application. I've updated it with my unique access_token.

However, my application throws an error that "you must include an access_token". I've tried moving the new data directory so it gets bundled along with the rest of my application files, but still no luck.

So now, every time I make a call I have to provide my access token as an arg. Any idea what is going on here? Thank you!

**Comment by vlavrynovych** [comment]
Do you have a similar structure of your project?
-- Project
---- bin
---- data
------ strava_config
---- lib
---- ....

**Comment by besseddrest** [comment]
Yes, but I'm using webpack to bundle everything and I think the data folder is not being included in the bundle; is there a specific way it should be included?

**Comment by HyperSprite** [comment]
I am guessing that if you are not importing the strava_config, it's not getting bundled. I had a similar issue and ended up making my own config file. As the readme states, we can use node environmental vars. At first I just added them to the server main file but this was cumbersome and made Heroku a setup a challenge.

So what I did was add this to the top of my server.js file, before any other imports. It looks for the config.js file and if it finds it, loads it. 
```js
const fs = require('fs');
const path = require('path');
if (fs.existsSync(`${__dirname}/config.js`)) {
  const config = require('./config');
  config.loadConfig();
}
```
In the same directory as my server.js file is config.js file that excluded via .gitignor. It has all of my env vars in it (I've redacted other stuff for clarity) and looks a bit like this:

```js
const config = {
  STRAVA_ACCESS_TOKEN: 'YOUR_ACCESS_TOKEN',
  STRAVA_CLIENT_ID: 'YOUR_KEY', // Strava API Key holders ID
  STRAVA_CLIENT_SECRET: 'YOUR_STRAVA_SECRET',
  STRAVA_REDIRECT_URI: 'auth/strava', // for Strava Auth
};

exports.loadConfig = () => {
  process.env.STRAVA_ACCESS_TOKEN = process.env.STRAVA_ACCESS_TOKEN || undefined;
  process.env.STRAVA_CLIENT_ID = process.env.STRAVA_CLIENT_ID || config.STRAVA_CLIENT_ID;
  process.env.STRAVA_CLIENT_SECRET = process.env.STRAVA_CLIENT_SECRET || config.STRAVA_CLIENT_SECRET;
  process.env.STRAVA_REDIRECT_URI = process.env.STRAVA_REDIRECT_URI || config.STRAVA_REDIRECT_URI;
};
``` 

Then for Heroku, there is no file, since it is .gitignored and I just add the production env vars to my Heroku config.

**Comment by besseddrest** [comment]
Thank you. It does not look like I am importing the file, so you are probably right, it's not getting bundled.

**Comment by markstos** [comment]
Note the example code by @HyperSprite contains a bug.  As documented in the Node.js [process docs](https://nodejs.org/api/process.html),  assigning a value to `process.env` always stringifies it. This includes the value "undefined".

So if `process.env.STRAVA_ACCESS_TOKEN` is undefined, you are going to end up setting `process.env.STRAVA_ACCESS_TOKEN` to the *string* "undefined" instead of the *value* `undefined`. 

The same could happen on the other lines if the "config" values are also undefined-- the result could be setting a value to the *string* undefined.

If you really want to "undefine" a `process.env` value, you have to delete the key:

     delete process.env.STRAVA_ACCESS_TOKEN

**Comment by schmeusel** [comment]
The `utils.postEndpoint(...)` method should not require an `access_token`, though, if `oauth.getToken(...)` is called. It will always return an error if the `access_token` is neither set through a config file nor an environment variable.
