### ISSUE TITLE
Include type information

### ISSUE THREAD

**Issue by Roaders** [UnbounDev/node-strava-v3#45]
including type information with this library would make use of it by third party developers much easier.

This would essentially mean converting this library to Typescript and transpiling the Ts files to js files (Which would be published to npm in the same way.
The end user would not see any difference (unless they wanted to use the types in which case life would be SO much easier).

Would you accept a pull request for this change?

**Comment by TimoSta** [comment]
I think converting the whole library to TypeScript and re-writing the source code is not necessarily a good idea because A) not everybody who develops JavaScript is comfortable writing TypeScript, effectively removing a chunk of the contributer base, which we should avoid unless there is a very good reason, and B) it introduces another step into the build process, which also increases the hurdle a potential contributer has to take.

With this in mind, would it be an acceptable compromise to instead write the TypeScript bindings manually and to leave the source files in JavaScript as they are right now? This appears to work fine for lots of other projects (see [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)), allows the usage of this library in TS applications and also avoids the concerns I listed above.

What are your thoughts on this?

**Comment by Roaders** [comment]
Well manually writing the bindings is error prone and time consuming (although I appreciate re-writing in Typescript will be time consuming as well). There is also a continued cost in maintaining the bindings.

If the library is written in Typescript this does not mean that people consuming the library have to use Typescript. The compiled JavaScript is what is added to npm and is what is installed when doing `npm install`. The difference is that when the JavaScript is created the bindings are also automatically created and perfectly match the compiled JS as they are created from the same code.
These bindings are included in the npm package and are ignored if you are a JavaScript developer but are invaluable if you are a TS developer.

**Comment by TimoSta** [comment]
I absolutely see your point that bindings are valuable and maintaining them manually is error prone and requires effort. I also realize that non-TS projects can still use compiled TS libraries.

I am more concerned about the contributers of the project than its users, since they are the ones most affected by it. Considering that TypeScript is still far less widely adopted than JavaScript (compare e.g. [StackOverflow's 2016 developer survey](http://stackoverflow.com/insights/survey/2016#technology-most-popular-technologies)), converting the complete project to TS would require every contributer to either know TypeScript already (which is very unlikely), or to read up on it's syntax, conventions and way of doing things (which we cannot realistically ask for).

Since the public API of the library should remain (more or less) stable within a major release anyway and since this is what we would have to cover with the TS bindings, I would consider the additional effort acceptable, especially considering the downsides of the alternative. If we find that we run into compatibility issues going forward, it would be a worth considering to write a suite of unit tests against the TS interface to ensure that the bindings are still valid and work with the JavaScript source. Since the tests are run automatically for every pull request, this would prevent a bad commit from being merged into the project.

I hope you understand my concerns?

**Comment by Roaders** [comment]
Yup, OK, That's fine.
