### ISSUE TITLE
Optionally return an observable if no done method passed

### ISSUE THREAD

**Issue by Roaders** [UnbounDev/node-strava-v3#46]
for example:

```
clubs.get({myArgs}, function(err,payload){
    //do stuff
});
```

would still work but if no function is passed as the second argument an observable would be returned:

```
clubs.get({myArgs})
    .flatMap(returnedClubList => Rx.Observable.return(returnedClubList ))
    .flatMap(club => clubs.listMembers({getMembersFor: club}))
    .subscribe(clubMember => console.log("club member: " + clubMember);
```

this would return a list of all club members from all clubs returned from the initial call.

Would you accept a pull request for this?

**Comment by TimoSta** [comment]
I really like the idea, as this results in a much nicer API in my opinion.

Any reason you would use observables rather than promises? I would argue that promises are the better choice here, as they also seem to cover all use cases, do not introduce an additional dependency to ReactiveX and keep the libray's API in line with the `fetch()` API etc:

```
const flatten = arr => arr.reduce((acc, cur) => acc.concat(cur), [])
strava.clubs.get({myArgs})
    .then(clubs => clubs.map(club => strava.clubs.listMembers({getMembersFor: club})))
    .then(flatten)
    .then(members => members.forEach(m => console.log('club member:', m);
```

**Comment by Roaders** [comment]
Observables are far more powerful and for example make error handling much easier:

```
strava.clubs.get({myArgs})
    .retry(3)
    .catch(error => doSomethingWithError())
    .subscribe();
```

They also allow for much more advanced composition. In your example above how to you know when all the club members have been returned? What if you wanted to add all the club members into an array or count them? You would need some state that you manage yourself to track which promises are still waiting to return and only when they are all done return the total count.

**Comment by Roaders** [comment]
You can also dispose of an Observable to stop it if you're no longer interested in the result.

**Comment by markstos** [comment]
I would recommend uses Promises instead. The promise of observables being "more powerful" is vague. Promises are already used by Mongoose, another popular Node.js module that is likely to be used in parallel.

I don't see how how Observables make error handling "much easier": Promise libraries have "catch" and "finally"  as well.

The "subscribe()" notion is awkward for REST API calls because they return a single response-- there is not a stream of events to subscribe to. 

> In your example above how to you know when all the club members have been returned? 

With a promise library like Bluebird, you can use the `all` method to wait until all promises are resolved.

http://bluebirdjs.com/docs/api/promise.all.html

> What if you wanted to add all the club members into an array or count them?

It seems they *are* an in `members` array in the examples above. If it's an array-of-arrays, then that could be flattened if needed. 

Oservables seems like overkill here.

**Comment by markstos** [comment]
I've now implemented a Promise-based API. The callback API is still there as well:

https://github.com/RideAmigosCorp/node-strava-v3/tree/ra-fixes

**Comment by richarddavenport** [comment]
Just found the library, I'm thinking of using it, and was looking for a promise based approach. I'm also a huge fan of rxjs too. I would like to see the library return promises if `done` is omitted. Then as an observable dev, you could create an observable from the promise using either the `from`, `fromPromise` or even `of` with the Observable api.

Since the strava api is based on rest, there isn't a reason to use streams or observables. Starting with promises and letting the dev create streams from the promises, I think, would be a good start.

let me know if PR's are accepted.

**Comment by markstos** [comment]
@richarddavenport there has been no feedback for months, so I wouldn't expect activity soon. I'm also hesitant to publish my fork and become a maintainer myself, but I think publishing the updated API as a fork is the logical next step now. You are welcome to use my `ra-fixes` branch, but perhaps we should discuss the best way to get that fork published. It has been solid in production for us for months, using it with dozens of customers.

**Comment by markstos** [comment]
Observables won't be implemented, but my Promise-based PR will be merged and released now that I'm maintainer. Closing this.
