### ISSUE TITLE
Unable to resolve module 'fs'

### ISSUE THREAD

**Issue by JoostSlijkoort** [UnbounDev/node-strava-v3#66]
When using the dependency in a React Native project, i receive the following error:

`Unable to resolve module 'fs' from node_modules/strava-v3/index.js`

I am running node version v6.10.2.

**Comment by msardi23** [comment]
Hitting the same issue, did you resolve this for your react native project?

**Comment by JoostSlijkoort** [comment]
No, i did not proceed.

**Comment by msardi23** [comment]
Thanks. Actually thinking about this a little more, it does not really make sense to include this within the React Native project itself anyway. Looking at how the Strava authentication process works, you will pretty much need to have a small Node.js server anyway (or at least that is what I am finding with React Native + Expo) otherwise you simply cannot get the oauth process to run smoothly.

**Comment by vlavrynovych** [comment]
This module is definitely for backend. And `fs` is a native module in a node.js. I would say that this discussion can be closed
