### ISSUE TITLE
Getting "done is not a function" when uploading file 

### ISSUE THREAD

**Issue by cvaldev** [UnbounDev/node-strava-v3#87]
Files are still uploaded, but I'm seeing this error in my logs: 
```
TypeError: done is not a function
at [redacted]/node_modules/strava-v3/lib/uploads.js:33:5
```
I'm using the API like this:
```js
const payload = await strava.uploads.post({
    access_token: accessToken,
    data_type: dataType,
    file: file
});
```

**Comment by markstos** [comment]
What version of  `node-strava-v3` are you using?

**Comment by cvaldev** [comment]
@markstos v2.0.5. I think this is where it's coming from: https://github.com/UnbounDev/node-strava-v3/blob/b11a542b643de9cd2755d31e6c02976175dc05ed/lib/uploads.js#L33

I noticed that If I pass an empty function as a second parameter then the error doesn't appear.

**Comment by markstos** [comment]
That's a bug. Looks like this function needs some extra work to be compatible with a promise-based API. 

It's a bit tricky because Promises have a single return value. What happened here was that the `done()` callback was called, but the function might have also called the `check` function, which would run in a loop until the upload was finished, then finally call the statusCallback when done. 

In a promise-based flow, I don't think we can keep the ordering exactly the same. I think we would have to call `self._check()` first and then `return payload`.

Are you able to help fix this and test with both the promise and callback-based APIs?

I suppose we could also drop the callback-based API and bump the major version.

**Comment by markstos** [comment]
If others run into this: switch to the promise API to avoid the bug. The callback API will be dropped eventually anyway.
